### ISSUE TITLE
BIWI dataset preprocessing

### ISSUE THREAD

**Issue by KVBK01** [uuembodiedsocialai/FaceDiffuser#10]
Sorry to disturb.
I see the BIWI dataprepocessing requires only to download the [faces0x.tgz] files, which is different from other preprocessing ways such as CodeTalker that requires other files like [scans0x.tgz].

I wonder if the provided preprocessing code outputs the exactly same precessed files as CodeTalker. 

Thanks again for the good work.

**Comment by galib360** [comment]
Hi, 
Thanks for raising the issue. You are correct, the paper results are based on the BIWI dataset processed by following CodeTalker (https://github.com/Doubiiu/CodeTalker/tree/main/BIWI) for fair comparison with previous works. The README has been updated with the correct information now. The old pre-processing steps are for a different project.

**Comment by UchihaBarry** [comment]
> Sorry to disturb. I see the BIWI dataprepocessing requires only to download the [faces0x.tgz] files, which is different from other preprocessing ways such as CodeTalker that requires other files like [scans0x.tgz].
> 
> I wonder if the provided preprocessing code outputs the exactly same precessed files as CodeTalker.
> 
> Thanks again for the good work.

hi, can you provide the biwi dataset? Since the office link is no longer valid, and i cant get this dataset
