### ISSUE TITLE
About the .flv file in BIWI dataset

### ISSUE THREAD

**Issue by KVBK01** [uuembodiedsocialai/FaceDiffuser#11]
Thanks again for the code. 

I am one more question about pre-processing the BIWI dataset. 
I have requested and obtained the download link of BIWI, which looks like this
![スクリーンショット 2023-11-09 155408](https://github.com/uuembodiedsocialai/FaceDiffuser/assets/39583895/f57987d1-5ed3-45b8-bef9-c1fdf172c124)

It seems like no .flv files are included in the download link, which should be included as suggested in the download page:
- 'videos' contains videos (.flv) of the rendered 3D geometries and original audio (sampling rate: 44.1kHz).

I wonder if i missed something and how the authors handle this problem. 
Thanks again if you could kindly reply.

**Comment by galib360** [comment]
The .flv's are either in the rest.tgz or the faces*.tgz archives as far as I remember.

**Comment by KVBK01** [comment]
Thanks! I have addressed this problem

**Comment by hrWong** [comment]
Hi @KVBK01 

I noticed your mention of using the BIWI 3D Audiovisual Corpus of Affective Communication (B3D(AC)^2) dataset in this context. I'm currently working on 3D facial animation.

I'm aware that the official distribution of B3D(AC)^2 has ceased. I was hoping to ask if you might be open to sharing your copy of the dataset for academic research purposes. I would, of course, strictly adhere to all original usage policies and ethical guidelines associated with it.

If sharing is not feasible, I would still greatly appreciate any advice you might have on accessing similar high-quality audio-visual 3D facial datasets.

Thank you for your time and consideration.
