### ISSUE TITLE
Do I need 1TB of RAM to run code? Or a hard drive?

### ISSUE THREAD

**Issue by paopao1027** [uuembodiedsocialai/FaceDiffuser#12]

**Comment by galib360** [comment]
No, for clarity and reproducibility in mind, the reported results in the paper are based on the model trained on the described machine (which us a shared compute cluster). However, we also tested it on a local machine (i.e. consumer laptop with 32 GB RAM, 6GB Nvidia GPU), so the machine described in the paper is not a system requirement for the model.
