### ISSUE TITLE
BIWI training sequence indices

### ISSUE THREAD

**Issue by dafei-qin** [uuembodiedsocialai/FaceDiffuser#2]
Thanks for your interesting work! I want to ask whether the model on BIWI is trained with only `e` sequences or not-`e` sequences or both.

In the paper it says only use the emotional sequences, but in the data_loader the training splits is `range(1, 33)`, which IMO is the non-emotional sequences?

**Comment by galib360** [comment]
Hi, 
The BIWI dataset was trained only on the emotional sequences (i.e.- e01-e40). However, when the data was preprocessed, the "e" sequences were renamed by removing the "e". E.g.- e01 was renamed to 01 and so on. For data pre-processing we borrowed the scrip from CodeTalker (https://github.com/Doubiiu/CodeTalker/tree/main/BIWI) to ensure proper comparison and encourage reproducibility. I hope that answers your question.

**Comment by galib360** [comment]
Edited the original comment for clarity.
