### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by Oocean35** [uuembodiedsocialai/FaceDiffuser#3]
Hi @uuembodiedsocialai , 
thanks a lot for sharing this insightful work ! 
I wanted to ask if you have plans to release the pretrained weights for the models (particularly the one trained with vocaset). That would be very helpful ! 

Thanks a lot :)

**Comment by galib360** [comment]
Hi, 
Thanks! We added the link to download the model weights in the repository. You can also use this link to download the model weights- https://mega.nz/folder/jlBF0Dpa#U3G1lJCZ4dijMoSc9gmqSg
